services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    hostname: adguardhome
    restart: always
    mac_address: ${adguardmac}
    networks:
      macvlan:
        ipv4_address: ${adguard4}
    volumes:
      - ./../adguardwork:/opt/adguardhome/work
      - ./:/opt/adguardhome/conf

networks:
  macvlan:
    external: true
    name: ${MACVLAN_NET}